"use strict";

globalThis.SolarLanguage = (() => {
  const translations = {
  "Space game: WASD thrust, K select satellite, L absorb, T jump, Space pause": "太空游戏：WASD 推进，K 选择卫星，L 吸收，T 跃迁，空格暂停",
  "A thought from the cosmos": "宇宙随想",
  "Body status": "天体状态",
  "Dashed rings: gravity and capture, cyan fleet detection, gold orbital gun range.": "虚线圈：引力与捕获范围；青色为舰队探测范围，金色为轨道炮射程。",
  "Artificial structures": "人造物",
  "No artificial structures yet.": "暂无人造物。",
  "Orbital gun": "轨道炮",
  "Carrier": "母舰",
  "Space city": "太空城",
  "Ship": "飞船",
  "Hull": "血量",
  "Build progress": "建造进度",
  "Building": "建造中",
  "Queued": "等待建造",
  "Build paused": "建造暂停",
  "Under fire": "受击中",
  "Repairing": "维修中",
  "Repair pending": "等待维修",
  "Low resources": "质量不足",
  "Operational": "运行中",
  "Recovering": "恢复中",
  "Docked": "已靠港",
  "Resupplying": "补给中",
  "Patrolling": "巡航中",
  "Attacking": "进攻中",
  "Harvesting": "采集中",
  "Returning": "返航中",
  "Devourer ship": "吞星船",
  "Deploying": "前往中",
  "Devouring": "吞噬中",
  "Recovering": "回收中",
  "Ammo": "弹药",
  "Cargo": "载货",
  "Endurance": "剩余续航",
  "Construction and repairs use core mass, except shields. Ships repair only while docked.": "除护盾外，建造与维修均消耗本体质量。飞船只能靠港维修。",
  "Shield construction unlocked": "护盾建造已解锁",
  "Orbital guns unlocked": "轨道炮已解锁",
  "Orbital carriers unlocked": "轨道母舰已解锁",
  "Fleet expansion unlocked": "舰队扩编已解锁",
  "Space city construction unlocked": "太空城建造已解锁",
  "Second city construction unlocked": "二级太空城建造已解锁",
  "Technology complete": "科技已全部掌握",
  "Research paused": "资源紧张，研究暂停",
  "Orbital guns · Build up to three rapid-fire, short-range defenses.": "轨道炮 · 逐个建造，最多三座，高攻速、近距离防卫。",
  "Space city · Build a city from core mass, beneath the outer shield.": "太空城 · 划拨本体质量建造，外层护盾继续保护城市。",
  "Double city · Add a second city ring and upgrade your ships.": "双层太空城 · 增加第二层城市环，并强化飞船。",
  "Destroy all artificial structures before mining a planet's core. Mining sharply reduces its population.": "摧毁行星所有人造产物后才能采集本体；采集会使人口锐减。",
  "Population accelerates research and construction. Below 1 M, civilization and all artificial structures perish.": "人口加快科研与建造；低于 1 百万时，文明及全部人造产物消亡。",
  "Build order: shield, guns, carriers, cities. Core damage pauses all construction for 5 seconds.": "建造顺序：护盾、轨道炮、母舰、城市。本体受损使所有建造暂停 5 秒。",
  "Asteroid Belt": "陨石带",
  "Nest Sector": "巢穴区",
  "Stellar System": "恒星系",
  "Dawn": "生命曙光",
  "Hearth": "星火家园",
  "Tribe": "群星部落",
  "Kinship": "星海同胞",
  "Citadel": "苍穹城邦",
  "Concord": "万民之约",
  "Dominion": "星际盛世",
  "Radiance": "文明辉光",
  "Ascendant": "群星崛起",
  "Celestial": "天穹国度",
  "Eternal": "永恒之民",
  "Infinity": "无尽繁荣",
  "Empyrean": "九天文明",
  "Cosmos": "宇宙之心",
  "Omniverse": "万象共生",
  "Mass": "质量",
  "Mass integrity": "质量完整度",
  "Breaks below": "毁灭线：低于",
  "Speed": "速度",
  "Satellites": "卫星",
  "Distance": "距离",
  "Time": "时间",
  "Population": "人口",
  "Steady flight keeps up to one third of your ships on patrol. Ships turn gradually and return to resupply.": "平稳航行时，最多三分之一的飞船在外巡航；舰船转向具有惯性，并定期返港补给。",
  "Carriers / ships": "母舰 / 飞船",
  "population": "人口",
  "Tech": "科技",
  "Shield": "护盾",
  "City mass": "太空城质量",
  "Battle record": "战绩",
  "Planets": "行星",
  "Nests": "巢穴",
  "Warning": "预警",
  "Incubating life": "生命孕育中",
  "Drift paused": "漂流暂停",
  "Pause controls": "暂停操作",
  "Resume": "继续",
  "Space": "空格",
  "Trail": "轨迹",
  "New journey": "新的旅程",
  "Drifting": "惯性漂流",
  "Gravity reach": "引力范围",
  "Capture reach": "捕获范围",
  "K select satellite · L absorb": "K 选择卫星 · L 吸收",
  "Zoom": "缩放",
  "Your journey is saved every second.": "每秒自动记录你的旅程。",
  "Your journey is safely recorded.": "你的旅程已妥善记录。",
  "Quick guide": "操作说明",
  "Celestial bodies": "天体图鉴",
  "THE UNIVERSE REMEMBERS": "宇宙会记得",
  "Back to stardust": "归于星尘",
  "Begin again": "再次启程",
  "CHOOSE YOUR ORIGIN": "选择你的起点",
  "Choose your origin": "从哪颗星开始？",
  "Choose a starting stage. Your civilization begins with new life.": "选择起始天体，文明从初生生命开始发展。",
  "Starting body": "起始天体",
  "Begin journey": "开始旅程",
  "Continue · New sandbox": "继续旅程 · 新宇宙",
  "WASD Thrust · K Select · L Absorb": "WASD 推进 · K 选择 · L 吸收",
  "T Jump · Wheel Zoom · Space Pause · O Trail": "T 跃迁 · 滚轮缩放 · 空格暂停 · O 轨迹",
  "Release WASD to coast; thrust backward to brake.": "松开 WASD 惯性滑行，反向推进制动。",
  "Merge asteroids at low speed. As a planet, fly past asteroids to capture them; K selects, L or double-click absorbs.": "陨石低速碰撞成长；行星掠过陨石捕获，K 选择，L 或双击吸收。",
  "Life and technology grow automatically. At tech 4, press T to jump: click to confirm, right-click / Esc to cancel.": "生命与科技自动发展。科技 4 级解锁 T 跃迁：左键确认，右键或 Esc 取消。",
  "Avoid hostile fire and massive bodies. Autosaves keep your progress; loading creates a new universe.": "避开敌方火力与大质量天体。自动存档保留成长，读档进入新宇宙。",
  "The nest has fallen silent": "巢穴已归于沉寂",
  "Hostile fire detected": "遭遇敌方火力",
  "A shield now shelters your world": "护盾开始守护你的世界",
  "Your civilization has learned to defend itself": "你的文明学会了抵御外敌",
  "Artificial moons take their first flight": "人造卫星首次升空",
  "A city rises beyond the sky · Jump unlocked": "城市延伸至天外 · 跃迁已解锁",
  "Your civilization has mastered stellar harvesting": "你的文明掌握了天体吞噬技术",
  "Life has emerged on your world": "你的世界诞生了生命",
  "A new chapter for your world": "你的世界翻开新篇章",
  "A new sky awaits": "一片新的星空在等待",
  "A powerful gravity well lies nearby": "附近发现强大引力源",
  "Your journey continues beneath unfamiliar stars": "你的旅程在陌生星空下继续",
  "Your world suffered critical damage.": "你的世界遭受了致命损伤。",
  "You were absorbed by a larger body.": "你被更大的天体吸收了。",
  "Peak mass": "最高质量",
  "absorbed": "已吸收",
  "bodies, drifted for": "颗天体，漂流",
  "years, travelled": "年，累计距离",
  "years": "年",
  "km": "千米",
  "Jump locked · Requires a space city": "跃迁尚未解锁 · 需要太空城",
  "Jump locked · Requires a level 4 space city": "跃迁尚未解锁 · 需要 4 级文明太空城",
  "Jump recharging": "跃迁充能中",
  "Jump cooldown": "跃迁冷却",
  "Jump obstructed · Choose open space": "跃迁受阻 · 请选择空旷地带",
  "Jump ready · T select, click confirm, right-click / Esc cancel": "跃迁就绪 · T 选点，左键确认，右键或 Esc 取消",
  "No save yet · Autosave starts with your journey.": "暂无存档 · 启程后自动保存。",
  "Invalid save data.": "存档内容无效。",
  "Unable to read save:": "无法读取存档：",
  "Save failed:": "保存失败：",
  "Thrust cap": "推进上限",
  "Speed cap": "速度上限",
  "Selected": "已选择",
  "L absorb": "L 吸收",
  "Signal lost": "信号消逝",
  "Time paused": "时间已暂停",
  "Thrusting · Release WASD to coast": "正在推进 · 松开 WASD 漂流",
  "Drifting · WASD to thrust": "惯性漂流 · WASD 推进",
  "Journey ended": "旅程结束",
  "Gravity paused": "引力已暂停",
  "Drifting among the stars": "在群星间漂流",
  "Next stage:": "下一阶段：",
  "Your world is fully grown · New mass expands the city": "你的世界已成长完全 · 新增质量用于扩建太空城",
  "World integrity": "世界完整度",
  "Keep above 30% to survive": "保持在 30% 以上以存活",
  "Mothership": "母舰",
  "Fighter": "攻击舰",
  "Asteroid": "陨石",
  "Planet": "行星",
  "Room for": "可容纳",
  "moons": "颗卫星",
  "Natural body": "天然天体",
  "Cannot be captured or destroyed": "无法捕获或摧毁",
  "Tech cap": "科技上限",
  "Satellite cap": "卫星上限",
  "Merge asteroids": "融合陨石",
  "Reach mass": "质量达到",
  "to incubate life": "即可孕育生命",
  "Life ready · Reach Luna": "孕育完成 · 等待皓月阶段",
  "Life re-emerging": "生命重新孕育",
  "Incubation": "孕育进度",
  "Absorb asteroids to mass": "吸收陨石，将质量提升至",
  "to unlock population capacity": "以解锁人口容量",
  "Seeds": "诞生",
  "needs population": "所需人口",
  "Research": "研究",
  "All technologies unlocked": "所有科技已解锁",
  "Growing · Tech capped": "人口增长 · 科技达当前上限",
  "Growing · Tech complete": "人口增长 · 科技完备",
  "Research cap": "研究上限",
  "Awaiting population": "等待人口增长",
  "Research resumes at the population threshold": "人口达标后继续研究",
  "Researching": "研究中",
  "Dust": "星尘",
  "Core": "星核",
  "Luna": "皓月",
  "Mars": "赤星",
  "Terra": "大地",
  "Gaia": "盖亚",
  "Halo": "星环",
  "Titan": "泰坦",
  "Sol": "恒星",
  "Pulsar": "脉冲星",
  "Void": "虚空",
  "The asteroid you just swallowed was their shooting star last night.": "你刚吞下的那颗陨石，是他们昨晚许愿的流星。",
  "They called your last sharp turn the Great Migration.": "他们把这次急转弯叫作“大迁徙”。",
  "After the first jump, every astronomer filed for retirement.": "第一次跃迁后，天文学家集体申请了退休。",
  "The day the shield went up, the doomsayers started looking for other work.": "护盾建成那天，末日预言家开始寻找别的工作。",
  "That moon kept them company for three centuries. You needed a little more mass.": "那颗卫星陪了他们三百年。你觉得还差一点质量。",
  "The expensive apartments face the star. The cheap ones will shortly.": "太空城最贵的房子朝向恒星，最便宜的也快朝向恒星了。",
  "They discovered the universe has no center. You remain in the middle of the screen.": "他们发现宇宙没有中心。你依然待在屏幕正中间。",
  "You let go of the controls. They entered an age of peace.": "你松开了方向键。他们迎来了和平年代。",
  "They spent centuries explaining your orbit. Let us hope they never discover WASD.": "他们花了几百年解释你的轨道。希望他们永远别发现 WASD。",
  "Their oldest calendar is now a work of fiction.": "他们最古老的历法，如今被归入了小说。",
  "The new moon has a name already. Please try not to eat this one.": "新月亮已经有名字了。这颗尽量别吃。",
  "Somewhere down there, someone is blaming the weather.": "下面的某个地方，有人正在埋怨天气。",
  "The ocean moved first. The maps followed reluctantly.": "海洋先搬了家，地图很不情愿地跟了过去。",
  "Their first message to the stars was a complaint about the rent.": "他们发往群星的第一条消息，是抱怨房租太贵。",
  "A child drew two moons today. By dinner, the drawing was out of date.": "今天有个孩子画了两个月亮。晚饭前，画就过时了。",
  "The observatory has stopped printing next year's star charts.": "天文台已经不再印刷明年的星图。",
  "They built a monument to the moon. The monument lasted longer.": "他们为月亮立了一座碑。碑留得更久。",
  "Every crater has a story. Most begin with an apology.": "每个陨石坑都有故事。大多以一句道歉开头。",
  "The first space tourist asked when the planet would stop moving.": "第一位太空游客问，这颗行星什么时候能停一下。",
  "They named a constellation after you. You promptly left it behind.": "他们用你的名字命名了一个星座。你转眼就把它甩在身后。",
  "The shield warranty does not cover black holes.": "护盾保修条款不包含黑洞。",
  "Someone just opened a seaside cafe. You have one job.": "刚有人开了一家海边咖啡馆。你稍微开稳一点。",
  "Their telescope found another civilization. Their laser found it too.": "望远镜发现了另一个文明。激光也发现了。",
  "The city council approved another floor. Gravity approved all of them.": "市议会批准再盖一层。引力批准了所有楼层。",
  "A billion people live here. None of them agreed on a name.": "这里住着十亿人。谁也没能说服谁该给这里起什么名字。",
  "They finally reached the moon. You were browsing for another.": "他们终于登上了月亮。你正在物色下一颗。",
  "The emergency siren is now the national anthem.": "紧急警报如今成了国歌。",
  "Their philosophers call it fate. You call it a missed turn.": "哲学家称之为命运。你称之为转弯没转过来。",
  "The stars look peaceful from a sufficiently small window.": "窗户足够小，星空看起来就很太平。",
  "They packed for the end of the world. It turned out to be a short trip.": "他们为世界末日打好了行李。结果只是一次短途旅行。",
  "Space — View controls": "空格键 — 查看操作说明",
  "Dust merges on gentle contact. Planets grow by capturing and absorbing asteroids.": "星尘通过低速碰撞融合；行星通过捕获、吸收陨石成长。",
  "More mass supports more life. Sol, Pulsar and Void are natural hazards.": "质量越大，能容纳的生命越多。恒星、脉冲星与虚空是天然危险天体。",
  "Technology levels": "科技等级说明",
  "Controls": "按键操作说明",
  "Shield · Protects your world.": "护盾 · 抵御撞击与攻击。",
  "Lasers · Defend against nearby enemies.": "激光 · 自动攻击附近敌人。",
  "Artificial moons · Stronger, longer-range firepower.": "人造卫星 · 提升火力与射程。",
  "Space city · More living space and spatial jumps.": "太空城 · 扩大人口容量，解锁跃迁。",
  "Harvesting · Absorb half the remaining mass of planets destroyed by your lasers.": "吞噬 · 吸收被自身激光击碎行星剩余质量的一半。",
  "Thrust; reverse to brake.": "推进，反向推进制动。",
  "Select / absorb a captured moon.": "选择 / 吸收已捕获的卫星。",
  "Double-click": "双击",
  "Absorb a captured moon.": "吸收已捕获的卫星。",
  "Choose a jump destination; click to confirm, right-click / Esc to cancel.": "选择跃迁位置，左键确认，右键或 Esc 取消。",
  "Wheel / O": "滚轮 / O",
  "Zoom / toggle trail.": "缩放 / 切换轨迹。",
  "View guide / resume.": "查看说明 / 继续游戏。",
  "Use Chinese": "使用中文",
  "Keeping billions alive is easy. The hard part is not steering them into the sun.": "养活几十亿人不难，难的是别把他们开进太阳里。",
  "Start as a rock. Grow until the people on it complain about housing prices.": "从一颗石头开始，直到上面的人开始抱怨房价。",
  "You wander through space. They write history about every turn.": "你负责在宇宙里闲逛，他们负责给每次转弯编写历史。",
  "Collect moons, nurture civilization, and occasionally inconvenience astronomers.": "收集月亮，培养文明，偶尔给天文学家添点麻烦。",
  "Raise a rock into an entire world. Then figure out where to steer it.": "把一颗石头养成整个世界，然后想想该往哪儿开。",
  "They search the stars for answers. You search for your next asteroid snack.": "他们仰望星空寻找答案，你正在找下一顿陨石。",
  "A space-drifting game where the passengers multiply, but never buckle up.": "一款太空漂流游戏，乘客会自行繁衍，但不会系安全带。",
  "There are no predetermined orbits here—just textbooks trying to keep up.": "这里没有预定的轨道，只有努力跟上你的教科书。",
  "Flight controls": "飞行操作",
  "Rotate your device to landscape.": "请将设备旋转至横屏。",
  "Hold to thrust · Release to drift": "按住推进 · 松手滑行",
  "Hold": "按住",
  "Hold open space to thrust; release to drift.": "按住空旷处朝该方向推进，松手惯性滑行。",
  "Double-tap": "双击",
  "Pinch": "双指捏合",
  "Zoom the view.": "缩放视野。",
  "Jump": "跃迁",
  "Tap Jump, then tap open space. Tap Jump again to cancel.": "点击跃迁，再点选空旷处；再次点击跃迁可取消。",
  "Space game: WASD thrust, K select satellite, L absorb, R recall, Space pause": "太空游戏：WASD 推进，K 选择卫星，L 吸收，R 召回，空格暂停",
  "Structural integrity": "结构完整度",
  "Fleet controls": "舰队操作",
  "Recall": "召回",
  "Supply / pressure": "供养 / 压力",
  "Upkeep": "供养消耗",
  "Tech level": "科技等级",
  "mass/year": "质量/年",
  "Ships away / total": "在外 / 飞船总数",
  "Recall hold": "禁航倒计时",
  "Active / learned": "运行 / 已掌握",
  "Ready": "就绪",
  "M": "百万",
  "Civilization under strain": "文明供养不足",
  "Rebuilding civilization": "文明恢复中",
  "Population balance": "人口平衡",
  "Point defense is online": "星球近防炮已就绪",
  "Your first orbital carrier is ready": "首艘轨道母舰已就绪",
  "The orbital fleet has expanded": "轨道舰队扩编",
  "A city rises beyond the sky": "太空城在天际升起",
  "A second city surrounds your world": "双层太空城环绕你的世界",
  "Stellar mining is now possible": "恒星采集技术已解锁",
  "Civilization has lost an operating level": "供养不足，文明运行等级下降",
  "Your civilization has fallen silent": "你的文明已归于沉寂",
  "Life begins at 10 M. Population grows toward the mass your world can support; overcrowding slows research and reduces population.": "生命从 10 百万人口起步，随主星供养能力增长；过度拥挤会减缓科研并使人口下降。",
  "Upkeep never breaks your world. Combat integrity below 30% is fatal; fresh mass helps repair it.": "供养不会摧毁主星。战斗完整度低于 30% 时破碎，补充质量可修复损伤。",
  "Sol and Pulsar can be mined at technology 7. Void cannot be mined.": "7 级科技可开采恒星与脉冲星，虚空无法开采。",
  "Incubation · Life takes 30 seconds to emerge.": "孕育 · 生命需要 30 秒诞生。",
  "Point defense · Slow, heavy shots against close threats.": "近防炮 · 慢射速、高伤害，拦截近距离威胁。",
  "One carrier · Three ships for combat and transport.": "单母舰 · 最多三架飞船，自动战斗与运输。",
  "Three carriers · Four ships each, with greater reach.": "三母舰 · 每舰四架飞船，活动范围扩大。",
  "Space city · Stronger shields, more living space and faster ship production.": "太空城 · 强化护盾，扩大供养规模，加快飞船生产。",
  "Double city · No population cap; stronger ships and larger cargo holds.": "双层太空城 · 人口无硬上限，飞船强化、货舱扩大。",
  "Stellar mining · Harvest mass from Sol and Pulsar.": "恒星采集 · 搬运恒星与脉冲星的质量。",
  "Ships mine asteroids and unshielded planets. Shields must be broken first. Cargo only becomes yours after unloading.": "飞船采集陨石及无护盾行星；有护盾时先击破护盾。货物靠港卸载后才归入主星。",
  "Ships need ammunition and life support. Recall before accelerating; ships that cannot return are lost.": "飞船需要弹药与续航补给。加速前先召回，无法返航的飞船会损毁。",
  "Return all ships; hold departures for 10 seconds.": "召回所有飞船，10 秒内禁止出航。",
  "Cannot be captured; technology 7 can mine it": "无法捕获，7 级科技可采集",
  "Cannot be captured or mined": "无法捕获或开采",
  "No save for this civilization era yet.": "新文明纪元暂无存档。",
  "Saved journeys": "已保存的旅程",
  "Record the journey.": "记录旅程。",
  "Journey recorded": "旅程已记录",
  "The first supply ship returned. Dinner was no longer a theory.": "第一艘补给船回来了。晚饭终于不再只是一个理论。",
  "Language": "语言",
  "Language preference could not be saved.": "语言偏好无法保存。",
  "s": "秒"
};
  translations.Danger = "危险";
  translations.Nearby = "接近";
  translations["Unable to read save. Check browser storage permissions."] = "无法读取存档，请检查浏览器存储权限。";
  translations["Save failed. Check browser storage permissions and available space."] = "保存失败，请检查浏览器存储权限与剩余空间。";
  const key = "aphelion-language";
  let language = "en";
  try { language = localStorage.getItem(key) === "zh" ? "zh" : "en"; }
  catch { /* 浏览器禁止存储时，本次会话仍可选择语言。 */ }
  const bindings = new Map();
  const terms = Object.keys(translations).sort((a, b) => b.length - a.length);
  const pattern = new RegExp("\\b(?:" + terms.map(term => term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|") + ")(?![A-Za-z])", "g");
  function translate(source) {
    return language === "en" ? source : source.replace(pattern, match => translations[match]);
  }
  function text(node, source) {
    const value = String(source);
    bindings.set(node, { source: value });
    node.textContent = translate(value);
  }
  function attribute(node, name, source) {
    node.dataset[name === "title" ? "englishTitle" : "englishAria"] = source;
    node.setAttribute(name, translate(source));
  }
  function refresh() {
    document.documentElement.lang = language === "en" ? "en" : "zh-CN";
    for (const [node, binding] of bindings) {
      if (!node.isConnected) { bindings.delete(node); continue; }
      if (node.nodeType === Node.ELEMENT_NODE && node.firstChild?.nodeType === Node.TEXT_NODE) {
        node.firstChild.textContent = translate(binding.source);
      } else {
        node.textContent = translate(binding.source);
      }
    }
    for (const node of document.querySelectorAll("[data-english-title]")) node.title = translate(node.dataset.englishTitle);
    for (const node of document.querySelectorAll("[data-english-aria]")) node.setAttribute("aria-label", translate(node.dataset.englishAria));
    for (const control of document.querySelectorAll("[data-language]")) control.checked = language === "zh";
  }
  function initialize() {
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    const nodes = [];
    while (walker.nextNode()) {
      const node = walker.currentNode;
      if (node.textContent.trim() && !["SCRIPT", "STYLE", "OPTION"].includes(node.parentElement.tagName)) nodes.push(node);
    }
    for (const node of nodes) text(node, node.textContent);
    for (const node of document.querySelectorAll("[title], [aria-label]")) {
      for (const name of ["title", "aria-label"]) if (node.hasAttribute(name)) attribute(node, name, node.getAttribute(name));
    }
    for (const control of document.querySelectorAll("[data-language]")) control.addEventListener("change", () => {
      language = control.checked ? "zh" : "en";
      refresh();
      try { localStorage.setItem(key, language); }
      catch { window.alert(translate("Language preference could not be saved.")); }
    });
    refresh();
  }
  initialize();
  return { text, attribute, translate, forget: node => bindings.delete(node) };
})();
